declaration:
  call: declare
  version: 0.1
  description: "Get manifest list"
  method: get
  accepts: json
  returns: json
  namespace: centops
  allowlist:
    params:
      - field: clientId
        type: string
        description: "Unique identifier of the client"
      - field: page
        type: number
      - field: pageSize
        type: number

check_for_required_parameters:
  switch:
    - condition: ${incoming.params.clientId == null}
      next: return_incorrect_request
  next: assign_parameters

assign_parameters:
  assign:
    client_id: ${incoming.params.clientId}
    page: ${incoming.params.page ?? 1}
    page_size: ${incoming.params.pageSize ?? 10}
  next: get_manifests

get_manifests:
  call: http.post
  args:
    url: "[#CENTOPS_RESQL]/get-manifests-by-client-id"
    body:
      client_id: ${client_id}
      page: ${page}
      page_size: ${page_size}
  result: manifests_result

transform:
  call: http.post
  args:
    url: "[#CENTOPS_DMAPPER_HBS]/transform-manifests"
    headers:
      type: "json"
    body:
      entries: ${manifests_result.response.body}
      page: ${page}
      pageSize: ${page_size}
  result: manifests

return_manifests:
  status: 200
  return: ${manifests.response.body}
  next: end

return_incorrect_request:
  status: 400
  return: "Required parameter missing: clientId"
  next: end
