declaration:
  call: declare
  version: 0.1
  description: "Get manifest details"
  method: get
  accepts: json
  returns: json
  namespace: centops
  allowlist:
    params:
      - field: clientId
        type: string
        description: "Unique identifier of the client"
      - field: manifestId
        type: string
        description: "Manifest Id"

check_for_required_parameters:
  switch:
    - condition: ${incoming.params.manifestId == null || incoming.params.clientId == null}
      next: return_incorrect_request
  next: get_manifest

get_manifest:
  call: http.post
  args:
    url: "[#CENTOPS_RESQL]/get-manifests-details"
    body:
      manifest_id: ${incoming.params.manifestId}
      client_id: ${incoming.params.clientId}
  result: results
  next: return_result

return_result:
  status: 200
  return: ${results.response.body[0]}
  next: end

return_incorrect_request:
  status: 400
  return: "Required parameter missing: manifestId, clientId"
  next: end
