declaration:
  call: declare
  version: 0.1
  description: "Delete manifest"
  method: delete
  accepts: json
  returns: json
  namespace: centops
  allowlist:
    params:
      - field: clientId
        type: string
        description: "Unique identifier of the client"
      - field: manifestId
        type: string
        description: "Manifest Id"
    headers:
      - field: cookie
        type: string
        description: "Cookie field"
      - field: x-forwarded-for
        type: string

check_for_required_parameters:
  switch:
    - condition: ${incoming.params.manifestId == null || incoming.params.clientId == null || incoming.headers == null || incoming.headers.cookie == null}
      next: return_incorrect_request
  next: call_create_user_log_template

call_create_user_log_template:
  template: "[#CENTOPS_PROJECT_LAYER]/log-user-request"
  requestType: templates
  body:
    method: "DELETE"
    path: "admin/clients/manifests/delete"
    ip_address: ${incoming.headers[Object.keys(incoming.headers).find(h => h.toLowerCase() === 'x-forwarded-for')] || 'unknown'}
  headers:
    cookie: ${incoming.headers.cookie}
  result: delete_manifest

delete_manifest:
  call: http.post
  args:
    url: "[#CENTOPS_RESQL]/delete-manifest"
    body:
      manifest_id: ${incoming.params.manifestId}
      client_id: ${incoming.params.clientId}
  result: results
  next: return_result

return_result:
  status: 204
  return: ${results.response.body}
  next: end

return_incorrect_request:
  status: 400
  return: "Required parameter missing: manifestId, clientId or cookie"
  next: end

return_get_user_info_error:
  status: 400
  return: "User details haven't been fetched"
  next: end
