declaration:
  call: declare
  version: 0.1
  description: "Create a new manifest"
  method: post
  accepts: json
  returns: json
  namespace: centops
  allowlist:
    body:
      - field: clientId
        type: string
        description: "Unique identifier of the client"
      - field: name
        type: string
        description: "Name of the manifest"
      - field: gitHelmBranch
        type: string
        description: "Helm git branch of a deployment"
      - field: helmValues
        type: string
        description: "Helm values of a deployment"
      - field: gitHelmRepository
        type: string
        description: "git repository"
      - field: gitHelmPath
        type: string
        description: "Helm path in the git repository"
    headers:
      - field: cookie
        type: string
        description: "Cookie field"

check_for_required_parameters:
  switch:
    - condition: ${incoming.body.clientId == null || incoming.body.gitHelmBranch == null || incoming.body.gitHelmPath == null || incoming.body.helmValues == null || incoming.body.gitHelmRepository || incoming.body.name == null || incoming.headers == null || incoming.headers.cookie == null}
      next: return_incorrect_request
  next: extract_request_params

extract_request_params:
  assign:
    client_id: ${incoming.body.clientId}
    name: ${incoming.body.name}
    git_helm_branch: ${incoming.body.gitHelmBranch}
    helm_values: ${incoming.body.helmValues}
    git_helm_repository: ${incoming.body.gitHelmRepository}
    git_helm_path: ${incoming.body.gitHelmPath}
  next: call_create_user_log_template

call_create_user_log_template:
  template: "[#CENTOPS_PROJECT_LAYER]/log-user-request"
  requestType: templates
  body:
    method: "POST"
    path: "admin/clients/manifests/create"
  headers:
    cookie: ${incoming.headers.cookie}
  result: create_manifest

create_manifest:
  call: http.post
  args:
    url: "[#CENTOPS_RESQL]/create-manifest"
    body:
      client_id: ${client_id}
      name: ${name}
      git_helm_branch: ${git_helm_branch}
      helm_values: ${helm_values}
      git_helm_repository: ${git_helm_repository}
      git_helm_path: ${git_helm_path}
  result: results
  next: return_result

return_result:
  status: 201
  return: "Manifest created successfully"
  next: end

return_incorrect_request:
  status: 400
  return: "Required parameter are missing: clientId, helmVersion or helmValues or cookie"
  next: end
